config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cars do
    resources :rentals, only: [:new, :create]
  end

  resources :rentals, only: [:show, :index, :edit, :update, :destroy]

  get '/rentals', to: 'rentals#pending'
  get '/rentals/:id/accept', to: 'rentals#accept', as: :accept_rental
  get '/rentals/:id/decline', to: 'rentals#decline', as: :decline_rental

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :rentals
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rentals
  # has_many :cars through: :rentals
  has_many :cars
  has_many :rented_cars, through: :rentals, source: :car
  has_many :incoming_rentals, through: :cars, source: :rentals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.save
    redirect_to cars_path(@car)
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car = Car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :number_of_doors, :number_of_seats, :mileage, :available, :color)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def index
    @user = current_user
    @outgoing_rentals = Rental.where(user: current_user)
    @cars = Car.where(user_id: current_user)
    @incoming_rentals = current_user.incoming_rentals.where(owner_approval: nil)
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @car = Car.find(params[:car_id])
    @rental.car = @car
  end

  def create
    @rental = Rental.new(rental_params)
    @car = Car.find(params[:car_id])
    @rental.car = @car
    @rental.user = current_user
    @rental.save
    redirect_to rentals_path
  end

  def edit
    @rental = Rental.find(params[:id])
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update(rental_params)
    @rental.save
    redirect_to rental_path(@rental)
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to rentals_path
  end


  def pending
    @rental = Rental.where(:owner_approval == nil)
  end

  def accept
    @rental = Rental.find(params[:id])
    @rental.owner_approval = true
    @rental.save
    redirect_to rentals_path
  end

  def decline
    @rental = Rental.find(params[:id])
    @rental.owner_approval = false
    @rental.save
  end

  private

  def rental_params
    params.require(:rental).permit(:date_rented, :date_return, :owner_approval)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/home.html.erb
<div class="video-overlay"></div>

<video class="sqs-html5-video" poster="https://s3-us-west-2.amazonaws.com/s.cdpn.io/15309/sp-poster.jpg" autoplay loop>
  <source src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/15309/developer-loop-1920x1080.webm" type="video/webm">
  <source src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/15309/developer-loop-1920x1080.mp4" type="video/mp4">
  <!--[if lt IE 9]>
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/15309/sp-poster-old-ie.jpg" class="ie8-poster">
  <![endif]-->
</video>

<div class="text-copy">
  <h1>Fullscreen Video w/overlay</h1>
  <p>Inspired by Squarespace's video overlay</p>
  <p class="controls">
    (<a href="#">toggle on/off</a>)
  </p>
</div>

app/views/cars/index.html.erb
<br>
<h2 class="text-center"><strong>Trending Cars in Montreal</strong></h2>
<br>

  <div class="row justify-content-center">
    <% @cars.each do |car| %>
      <div class="card">
        <div class="card-img" style="background-image:url(<%= car.url %>);">
          <div class="overlay">
            <div class="overlay-content">
              <%= link_to "View", car_path(car), class: "hover" %>
            </div>
          </div>
        </div>

        <div class="card-content">
          <%= link_to car_path(car) do %>
            <p><strong><%= car.make %>&nbsp;&nbsp;<%= car.model %>&nbsp;&nbsp;<%= car.year %></strong></p>
            <p>Rate: $<%= car.price_per_day %>/day</p>
          <%end%>
        </div>
      </div>
    <% end %>
  </div>

app/views/cars/new.html.erb
<br>
<h1><center>Create a new listing</center></h1>
<h3><center>Enter car details below</center></h3>

<div class="container">
  <%= simple_form_for([@car]) do |f| %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :number_of_doors %>
    <%= f.input :number_of_seats %>
    <%= f.input :mileage %>
    <%= f.input :color %>
    <%= f.input :price_per_day %>
    <%= f.submit value="Create" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<html>
  <head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <br>
    <h2 class="text-center"><strong>Details</strong></h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card">
          <div class="card-img" style="background-image:url(<%= @car.url %>);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 12px;"><strong>Make:</strong> <%= @car.make %></span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Model:</strong> <%= @car.model %></span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Year:</strong> <%= @car.year %></span>
              <span style="margin: 12px;"><strong>Price:</strong> $<%= @car.price_per_day %></span>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-img" style="background-image:url(https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605832988/Exotic%20Cars/User%20Faces/interior_car_tmxdbd.jpg);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 10px;"><strong>Color:</strong> <%= @car.color %></span>
              <span style="margin: 10px;"><strong>Seats:</strong> <%= @car.number_of_seats %></span>
            </div>
            <br>
            <div>
              <span style="margin: 10px;"><strong>Doors:</strong> <%= @car.number_of_doors %></span>
              <span style="margin: 10px;"><strong>Mileage:</strong> <%= @car.mileage %></span>
            </div>
            <br>
            <button type="button" class="btn btn-outline-secondary" style="margin-left: 55px;"><%= link_to 'Book Now', new_car_rental_path(@car) %></button>
          </div>
        </div>
        <div class="card">
          <div class="card-img" style="background-image:url(<%= @car.user.url %>);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 10px;"><strong>Owner:</strong> <%= @car.user.username.capitalize %></span>
            </div>
            <br>
            <div>
              <span style="margin: 10px;"><strong>Star Rating:&nbsp;</span>
            </div>
            <div style="margin: 10px;">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span>(38)</span>
            </div>
          </div>
        </div>
      </div>
    </div>
<br>
    <h2 class="text-center"><strong>More cars from <%= @car.user.username.capitalize %></strong></h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card">
          <div class="card-img" style="background-image:url(https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605807889/Exotic%20Cars/Lambo-SUV_deybew.jpg);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 12px;"><strong>Make:</strong> Lamborghini</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Model:</strong> Urus</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Year:</strong> 2020</span>
              <span style="margin: 12px;"><strong>Price:</strong> $1000</span>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-img" style="background-image:url(https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605807888/Exotic%20Cars/bugatti_tmzx0m.jpg);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 12px;"><strong>Make:</strong> Bugatti</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Model:</strong> Chiron</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Year:</strong> 2019</span>
              <span style="margin: 12px;"><strong>Price:</strong> $1500</span>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-img" style="background-image:url(https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605807888/Exotic%20Cars/audi-r8-onlocation_gn9i1l.jpg);">
            <div class="overlay">
              <div class="overlay-content">
              </div>
            </div>
          </div>
          <div class="card-content">
            <div>
              <span style="margin: 12px;"><strong>Make:</strong> Audi</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Model:</strong> R8 V10</span>
            </div>
            <br>
            <div>
              <span style="margin: 12px;"><strong>Year:</strong> 2020</span>
              <span style="margin: 12px;"><strong>Price:</strong> $750</span>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" unless controller_name == "pages" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <div class="fullscreen-overlay"></div> -->

  <div class="buffer fullscreen">
    <!-- <h1 class="overlay-logo"><strong>VROOM</strong></h1> -->
    <img src='https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605822276/Exotic%20Cars/User%20Faces/logo_pk5nbb.png' class="overlay-logo" alt="...">
    <h3 class="overlay-text">Driving your dream car is just a click away...</h3>
    <%= link_to "Get Started", cars_path, class: "btn btn-outline-light overlay-button" %>
    <picture>
      <source media="(max-aspect-ratio: 4/3)"/>
      <img class="fullscreen-pic" srcset="https://cdn.wallpapersafari.com/86/22/6oFJfO.jpg"/>
    </picture>
  </div>

app/views/rentals/index.html.erb
<br>
<h3 class="text-center"><strong>Manage Your Rentals</strong></h3>
<br>
<div class="container">
  <div class="bookings-index-container">
    <div class="bookings-index-left mr-5">
      <div class="header-2">
      <h4><strong> My Listings </strong></h4>
      </div>
      <div class="container-rental">
        <img src="https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605808279/Exotic%20Cars/Alfa-Romeo-Tipo_yivwva.jpg"/>
        <div class="card-rental-infos pt-4">
          <h5><strong>Porsche&nbsp;&nbsp;911</strong></h5>
          <div>
            <span><strong>Doors: 2</strong></span>
            <span style="margin-left: 10px;"><strong>Seats: 4</strong></span>
          </div>
          <div>
            <span><strong>Year: 2021</strong></span>
            <br>
            <span><strong>Rate: $400</strong></span>
          </div>
        </div>
      </div>
    </div>

    <div class="bookings-index-right">
      <div class="header-2">
        <h4> Pending Approval </h4>
      </div>
      <%if @incoming_rentals.length == 0%>
        <div class="container-nill">
          <img src="https://previews.123rf.com/images/keltmd/keltmd1709/keltmd170900573/86958540-comic-speech-bubble-with-expression-text-oops-comic-speech-bubble-black-simple-silhouette-vector-ill.jpg" >
          <div class="card-nill-infos pt-4">
          <p><strong>No rental requests</strong></p>
        </div>
        </div>
      <% else %>
        <% @incoming_rentals.each do |rental| %>
          <div class="container-rental">
            <img src="https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605807889/Exotic%20Cars/lambo_db1xsb.png" />
            <div class="card-rental-infos pt-4">
              <p><strong>Your Vehicle:</strong> <%= rental.car.make  %> <%= rental.car.model  %> </p>
              <p><strong>Requested by User:</strong> <%= rental.user.username %> </p>
              <p><strong>Pick-up Date:</strong> <%= rental.date_rented.to_formatted_s(:long) %> </p>
              <p><strong>Return Date:</strong> <%= rental.date_return.to_formatted_s(:long) %> </p>
              <%= link_to "Approve", accept_rental_path(rental), class: "btn btn-success btn-sm" %>
              <%= link_to "Reject", decline_rental_path(rental), class: "btn btn-danger btn-sm" %>
            </div>
          </div>
        <% end %>
      <%end%>
        <div class="header-2">
          <h4> My Rentals </h4>
        </div>
        <%if @outgoing_rentals.length == 0%>
        <div class="container-nill">
          <img src="https://previews.123rf.com/images/keltmd/keltmd1709/keltmd170900573/86958540-comic-speech-bubble-with-expression-text-oops-comic-speech-bubble-black-simple-silhouette-vector-ill.jpg" >
          <div class="card-nill-infos pt-4">
          <span><strong>No rental requests</strong></span>
          <span><strong> ..make one? </strong></span>
          <%= link_to "Browse cars", cars_path, class: "btn btn-success" %>

          <%else%>
      <% @outgoing_rentals.each do |rental| %>
        <div class="container-rental">
          <img src="https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605807889/Exotic%20Cars/rezvani-tank_i4bhhx.jpg" />
          <div class="card-rental-infos">
            <h2><strong>Vehicle:</strong> <%= rental.car.make  %> <%= rental.car.model  %></h2>
            <p><strong>Pick-up Date:</strong> <%= rental.date_rented.to_formatted_s(:long) %> </p>
            <p><strong>Return Date:</strong> <%= rental.date_return.to_formatted_s(:long) %> </p>
            <% if rental.owner_approval == nil %>
              <p><strong>Owner confirmation: </strong><span style="color: #ff6200">Pending</span></p>
            <% elsif rental.owner_approval == true %>
              <p><strong>Owner confirmation: </strong><span style="color: green">Confirmed</span></p>
            <% else rental.owner_approval == false %>
              <p><strong>Owner confirmation: </strong><span style="color: red">Rejected</span></p>
            <% end %>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/new.html.erb
<br>
<h3><center>Book a <%= @rental.car.make %>&nbsp;<%= @rental.car.model %></center></h3>


<div class="container">
  <%= simple_form_for([@car, @rental]) do |f| %>
    <%= f.input :date_rented, html5: true %>
    <%= f.input :date_return, html5: true %>
    <%= f.input :owner_approval, :as => :hidden %>
    <%= f.submit value="Confirm" %>
  <% end %>
</div>

app/views/rentals/pending.html.erb
<% @rentals.each do |rental| %>
  <div class="container-rental">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-rental-infos pt-4">
      <p><strong>Your Vehicle:</strong> <%= rental.car.make  %> <%= rental.car.model  %> </p>
      <p><strong>Requested by User:</strong> <%= rental.user.username %> </p>
      <p><strong>Pick-up Date:</strong> <%= rental.date_rented.to_formatted_s(:long) %> </p>
      <p><strong>Return Date:</strong> <%= rental.date_return.to_formatted_s(:long) %> </p>
      <%= link_to "Approve", accept_rental_path(rental), class: "btn btn-success btn-sm" %>
    </div>
    <div class="owner-buttons">

    </div>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
        <!-- <form class="pure-form">
          <input type="text" class="pure-input-rounded" />
          <button type="submit" class="pure-button">Search</button>
        </form> -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="main-nav">
    <img class="navbar-brand" src="https://res.cloudinary.com/dl6q8gfk9/image/upload/v1605822276/Exotic%20Cars/User%20Faces/logo_pk5nbb.png" style="max-width: 150px;" href="" alt="">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse form-inline" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
         <li class="nav-item mr-2">
            <p class="nav-link no-margin"><%= link_to "Home", "/cars", class: "nav-link" %></p>
         </li>
         <li class="nav-item mr-2">
            <p class="nav-link no-margin"><%= link_to "My Dashboard", "/rentals", class: "nav-link" %></p>
         </li>
         <li class="nav-item mr-2">
            <p class="nav-link no-margin"><%= link_to "New Listing", '/cars/new', class: "nav-link" %></p>
          </li>

         <% if user_signed_in? %>

            <li class="nav-item mr-2">
               <p class="nav-link no-margin">Welcome, <%= current_user.username.capitalize %></p>
            </li>
            <li class="nav-item mr-2">
               <p class="nav-link no-margin"><%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-dark nav-item mr-2", id: "btn-account", method: :delete %></p>
            </li>
            <li class="nav-item">
              <%= image_tag "https://www.shareicon.net/data/512x512/2015/10/08/653048_users_512x512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
            </li>
         </div>
         <% else %>

            <li class="nav-item">
               <p class="nav-link"><%= link_to "Sign in", new_user_session_path, class: "btn btn-dark nav-item mr-2", id: "btn-account" %></p>
            </li>
            <li>
               <p class="nav-link"><%= link_to "Register", new_user_registration_path, class: "btn btn-dark nav-item mr-2", id: "btn-account" %></p>
            </li>

         <% end %>
      </ul>
      </ul>
   </div>
</div>
</div>